### ISSUE TITLE
With 3.07 cjs import is not working

### ISSUE THREAD

**Issue by coinnect-project** [muratgozel/MIMEText#42]
Hi,
with version 3.07 the cjs import gives error on startup. 3.06 is ok 
`// cjs
const {createMimeMessage} = require('mimetext')`

bye

**Comment by marc-wittwer** [comment]
This is the error i'm facing:
```
/home/user/Development/ts-api-2/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/user/Development/ts-api-2/node_modules/mimetext/dist/node/mimetext.cjs.js from /home/user/Development/ts-api-2/src/mailQueue.ts not supported.
mimetext.cjs.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename mimetext.cjs.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/user/Development/ts-api-2/node_modules/mimetext/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at require.extensions.<computed> [as .js] (/home/user/Development/ts-api-2/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/home/user/Development/ts-api-2/src/mailQueue.ts:17:20)
    at m._compile (/home/user/Development/ts-api-2/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/home/user/Development/ts-api-2/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/home/user/Development/ts-api-2/src/services/user.service.ts:31:21)
    at m._compile (/home/user/Development/ts-api-2/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/home/user/Development/ts-api-2/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/home/user/Development/ts-api-2/src/services/organisation.service.ts:23:24)
    at m._compile (/home/user/Development/ts-api-2/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/home/user/Development/ts-api-2/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/home/user/Development/ts-api-2/src/services/event.service.ts:25:32)
    at m._compile (/home/user/Development/ts-api-2/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/home/user/Development/ts-api-2/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/home/user/Development/ts-api-2/src/routes/event.route.ts:8:41)
    at m._compile (/home/user/Development/ts-api-2/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/home/user/Development/ts-api-2/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/home/user/Development/ts-api-2/src/main.router.ts:7:39)
    at m._compile (/home/user/Development/ts-api-2/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/home/user/Development/ts-api-2/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/home/user/Development/ts-api-2/src/app.ts:12:39)
    at m._compile (/home/user/Development/ts-api-2/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/home/user/Development/ts-api-2/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/home/user/Development/ts-api-2/src/server.ts:31:31)
    at m._compile (/home/user/Development/ts-api-2/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/home/user/Development/ts-api-2/node_modules/ts-node/dist/index.js:859:16) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by muratgozel** [comment]
hi @coinnect-project @marc-wittwer just fixed this, could you try again and let me know please?

**Comment by marc-wittwer** [comment]
@muratgozel 
Thanks, for fixing it. It is working now.

This also threw a linter error:
```
message.setSender(
        {
          addr: 'abc@mail.com',
          name: 'My Team',
        } 
      );
```
Linter-Error: An argument for 'config' was not provided. Expected 2 arguments, but got 1.

**Comment by marc-wittwer** [comment]
@muratgozel 

I ran into the following errors during an `npm run build` in the latest version.

```
node_modules/mimetext/types/index.d.ts:50:55 - error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

50         new(envctx: EnvironmentContext, data: string, headers = {}): MIMEMessageContent
                                                         ~~~~~~~~~~~~

node_modules/mimetext/types/index.d.ts:81:23 - error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

81         getRecipients(config: {type: MailboxType} = {type: 'To'}): Mailbox | Mailbox[] | undefined
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/mimetext/types/index.d.ts:144:9 - error TS2411: Property ''Content-Type'' of type 'string | undefined' is not assignable to 'string' index type 'string'.

144         'Content-Type'?: string,
            ~~~~~~~~~~~~~~

node_modules/mimetext/types/index.d.ts:145:9 - error TS2411: Property ''Content-Transfer-Encoding'' of type 'ContentTransferEncoding | undefined' is not assignable to 'string' index type 'string'.

145         'Content-Transfer-Encoding'?: ContentTransferEncoding,
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/mimetext/types/index.d.ts:146:9 - error TS2411: Property ''Content-Disposition'' of type 'string | undefined' is not assignable to 'string' index type 'string'.

146         'Content-Disposition'?: string,
            ~~~~~~~~~~~~~~~~~~~~~

node_modules/mimetext/types/index.d.ts:147:9 - error TS2411: Property ''Content-ID'' of type 'string | undefined' is not assignable to 'string' index type 'string'.

147         'Content-ID'?: string,
            ~~~~~~~~~~~~
```

**Comment by marc-wittwer** [comment]
@muratgozel 
I created a PR to fix the types: https://github.com/muratgozel/MIMEText/pull/43/files

**Comment by muratgozel** [comment]
thank you @marc-wittwer i dont know why i didnt get those errors. just published the fix.

**Comment by marc-wittwer** [comment]
thanks :+1:
